import { descriptions, overviews } from './api_project_descriptions';
import projectImages from '../assets/images/project_images/project_images';
import tech from './api_technologies';

const projects = [
  {
    id: 0,
    title: 'Hunting Buddy',
    className: 'hunting-buddy',
    description: descriptions.huntingBuddy,
    overview: overviews.huntingBuddy,
    projectLink: 'http://hunting-buddy.onrender.com',
    codeLink: 'https://github.com/katieloesch/hunting-buddy',
    imgArr: projectImages.huntingBuddy,
    tags: ['React', 'MERN', 'Full-Stack', 'Responsive Design', 'All'],
    skills: [
      tech.react,
      tech.javascript,
      tech.nodejs,
      tech.express,
      tech.mongodb,
      tech.mongoose,
      tech.vite,
      tech.postman,
      // tech.styledcomponents
    ],
  },
  {
    id: 1,
    title: 'PlaceBook',
    className: 'placebook',
    description: descriptions.placebook,
    overview: overviews.placebook,
    projectLink: 'https://placebook.katieloesch.co.uk/',
    codeLink: 'https://github.com/katieloesch/placebook',
    imgArr: projectImages.placebook,
    tags: ['React', 'MERN', 'Full-Stack', 'Responsive Design', 'All'],
    skills: [
      tech.react,
      tech.javascript,
      tech.nodejs,
      tech.express,
      tech.mongodb,
      tech.mongoose,
      tech.sass,
      // tech.postman,
      // tech.heroku,
    ],
  },
  {
    id: 2,
    title: 'Pawnee Pets',
    className: 'pawnee-pets',
    description: descriptions.pawneePets,
    overview: overviews.pawneePets,
    projectLink: 'http://pawnee-pets.katieloesch.co.uk',
    codeLink: 'https://github.com/katieloesch/project4-react-frontend',
    imgArr: projectImages.pawneePets,
    tags: ['React', 'Rails', 'Full-Stack', 'Responsive Design', 'All'],
    skills: [
      tech.react,
      tech.ruby,
      tech.rails,
      tech.css,
      tech.javascript,
      // tech.heroku,
      // tech.jwt,
      tech.postman,
    ],
  },
  {
    id: 3,
    title: 'Film & TV Stuff',
    className: 'flicks4brains',
    description: descriptions.flicks4brains,
    overview: overviews.flicks4brains,
    projectLink: 'http://film-tv-stuff.katieloesch.co.uk',
    codeLink:
      'http://github.com/katieloesch/project-2-react-film-app-revisited',
    imgArr: projectImages.flicks4brains,
    tags: ['React', 'Full-Stack', 'Responsive Design', 'All'],
    skills: [
      tech.javascript,
      tech.react,
      tech.sass,
      tech.firebase,
      tech.firestore,
    ],
  },
  // {
  //   id: 4,
  //   title: 'ConTemplate',
  //   className: 'contemplate',
  //   description: descriptions.contemplate,
  //   overview: overviews.contemplate,
  //   projectLink: '',
  //   codeLink: 'https://github.com/katieloesch/contemplate-frontend',
  //   imgArr: projectImages.contemplate,
  //   tags: ['Angular', 'Rails', 'Full-Stack', 'Responsive Design', 'All'],
  //   skills: [
  //     tech.rails,
  //   ],
  // },
  // {
  //   id: 6,
  //   title: 'Tic Tac Toe',
  //   className: 'browser-arcade',
  //   description: descriptions.browserArcade,
  //   overview: overviews.browserArcade,
  //   projectLink: 'http://tictactoe.katieloesch.co.uk/',
  //   codeLink: 'http://github.com/katieloesch/project-1-tictactoe',
  //   imgArr: projectImages.arcade,
  //   tags: ['React', 'Responsive Design', 'All'],
  //   skills: [tech.javascript, tech.html, tech.css],
  // },
];

export { projects };
