import { skillIcons } from '../assets/icons/icons_skills';

const technologies = {
  angular: {
    name: 'Angular',
    icon: skillIcons.angular_primary,
    id: 'angular-icon',
    alt: 'angular icon',
  },
  aws: {
    name: 'aws',
    icon: skillIcons.aws_primary,
    id: 'aws-icon',
    alt: 'aws icon',
  },
  bootstrap: {
    name: 'Bootstrap',
    icon: skillIcons.bootstrap_primary,
    id: 'bootstrap-icon',
    alt: 'bootstrap icon',
  },
  css: {
    name: 'CSS',
    icon: skillIcons.css_primary,
    id: 'css-icon',
    alt: 'css icon',
  },
  csharp: {
    name: 'C#',
    icon: skillIcons.csharp_primary,
    id: 'csharp-icon',
    alt: 'c sharp icon',
  },
  express: {
    name: 'express',
    icon: skillIcons.express_primary,
    id: 'express-icon',
    alt: 'express icon',
  },
  firebase: {
    name: 'Firebase',
    icon: skillIcons.firebase_primary,
    id: 'firebase-icon',
    alt: 'firebase icon',
  },
  firestore: {
    name: 'Cloud Firestore',
    icon: skillIcons.firestore_primary,
    id: 'firestore-icon',
    alt: 'cloud firestore icon',
  },
  git: {
    name: 'git',
    icon: skillIcons.git_primary,
    id: 'git-icon',
    alt: 'git icon',
  },
  github: {
    name: 'GitHub',
    icon: skillIcons.github_primary,
    id: 'github-icon',
    alt: 'github icon',
  },
  heroku: {
    name: 'Heroku',
    icon: skillIcons.heroku_primary,
    id: 'heroku-icon',
    alt: 'heroku icon',
  },
  html: {
    name: 'HTML',
    icon: skillIcons.html_primary,
    id: 'html-icon',
    alt: 'html icon',
  },
  java: {
    name: 'Java',
    icon: skillIcons.java_primary,
    id: 'java-icon',
    alt: 'java icon',
  },
  javascript: {
    name: 'JavaScript',
    icon: skillIcons.javascript_primary,
    id: 'javascript-icon',
    alt: 'javascript icon',
  },
  jwt: {
    name: 'JWT',
    icon: skillIcons.jwt_primary,
    id: 'jwt-icon',
    alt: 'jwt icon',
  },
  mongodb: {
    name: 'mongoDB',
    icon: skillIcons.mongodb_primary,
    id: 'mongodb-icon',
    alt: 'mongodb icon',
  },
  mongoose: {
    name: 'mongoose',
    icon: skillIcons.mongoose_primary,
    id: 'mongoose-icon',
    alt: 'mongoose icon',
  },
  nodejs: {
    name: 'Node.js',
    icon: skillIcons.nodejs_primary,
    id: 'nodejs-icon',
    alt: 'node.js icon',
  },
  openai: {
    name: 'OpenAI',
    icon: skillIcons.openai_primary,
    id: 'openai-icon',
    alt: 'openAI icon',
  },
  passport: {
    name: 'Passport.js',
    icon: skillIcons.passport_primary,
    id: 'passport-icon',
    alt: 'passport.js icon',
  },
  postgresql: {
    name: 'PostgreSQL',
    icon: skillIcons.postgresql_primary,
    id: 'postgresql-icon',
    alt: 'postgreSQL icon',
  },
  postman: {
    name: 'Postman API',
    icon: skillIcons.postman_primary,
    id: 'postman-icon',
    alt: 'postman api icon',
  },
  react: {
    name: 'React.js',
    icon: skillIcons.react_primary,
    id: 'react-icon',
    alt: 'react.js icon',
  },
  redux: {
    name: 'Redux',
    icon: skillIcons.redux_primary,
    id: 'redux-icon',
    alt: 'redux icon',
  },
  rails: {
    name: 'Ruby on Rails',
    icon: skillIcons.rails_primary,
    id: 'rails-icon',
    alt: 'ruby on rails icon',
  },
  ruby: {
    name: 'Ruby',
    icon: skillIcons.ruby_primary,
    id: 'ruby-icon',
    alt: 'ruby icon',
  },
  sass: {
    name: 'Sass',
    icon: skillIcons.sass_primary,
    id: 'sass-icon',
    alt: 'sass icon',
  },
  tailwind: {
    name: 'Tailwind CSS',
    icon: skillIcons.tailwind_primary,
    id: 'tailwind-icon',
    alt: 'tailwindCSS icon',
  },
  vite: {
    name: 'Vite',
    icon: skillIcons.vite_primary,
    id: 'vite-icon',
    alt: 'vite icon',
  },
  python: {
    name: 'Python',
    icon: skillIcons.python_primary,
    id: 'python-icon',
    alt: 'python icon',
  },
  typescript: {
    name: 'TypeScript',
    icon: skillIcons.typescript_primary,
    id: 'typescript-icon',
    alt: 'typescript icon',
  },
  go: {
    name: 'Go',
    icon: skillIcons.go_primary,
    id: 'go-icon',
    alt: 'go icon',
  },
  linux: {
    name: 'Linux',
    icon: skillIcons.ubuntu_primary,
    id: 'linux-icon',
    alt: 'linux icon',
  },
};

export default technologies;
